name: chat_app
description: A new Flutter project.
publish_to:
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  assets_audio_player: ^3.1.1
  audioplayers: ^3.0.1
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.8.5
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  firebase_messaging: ^14.7.2
  firebase_storage: ^11.4.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  intl: ^0.18.1
  just_audio: ^0.9.35
  math_expressions: ^2.4.0
  modal_progress_hud_nsn: ^0.4.0
  photo_view: ^0.14.0
  record: ^4.4.4
  shimmer: ^3.0.0
  syncfusion_flutter_sliders: ^20.4.51
  voice_message_package: ^1.0.41

dev_dependencies:
  flutter_lints: ^2.0.3
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.jpg"
  min_sdk_android: 21

  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/audio/Notification.mp3

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
