// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyLA2ECWnS0kWBwxJdwArm7keAGPGN_2I',
    appId: '1:108077877771:web:6258b53a62887ca19e150e',
    messagingSenderId: '108077877771',
    projectId: 'chat-app-9809a',
    authDomain: 'chat-app-9809a.firebaseapp.com',
    storageBucket: 'chat-app-9809a.appspot.com',
    measurementId: 'G-ZTM7FNNY2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTi9ouGI_C0kXLcXMKp1_7uSKfCe807pE',
    appId: '1:108077877771:android:f4600e63b3c0e59b9e150e',
    messagingSenderId: '108077877771',
    projectId: 'chat-app-9809a',
    storageBucket: 'chat-app-9809a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBog5oFyWjMLStALc_I8aOhuTL444vJw30',
    appId: '1:108077877771:ios:080cf397327abb119e150e',
    messagingSenderId: '108077877771',
    projectId: 'chat-app-9809a',
    storageBucket: 'chat-app-9809a.appspot.com',
    iosClientId: '108077877771-hpuqbo649ptk6n1ggb49n0ecpl3nsosu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBog5oFyWjMLStALc_I8aOhuTL444vJw30',
    appId: '1:108077877771:ios:080cf397327abb119e150e',
    messagingSenderId: '108077877771',
    projectId: 'chat-app-9809a',
    storageBucket: 'chat-app-9809a.appspot.com',
    iosClientId: '108077877771-hpuqbo649ptk6n1ggb49n0ecpl3nsosu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
